//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TtoCtrlPlatform.rc
//
#define IDD_TTOCTRLPLATFORM_DIALOG      102
#define IDR_HTML_CODE1DIALOG            103
#define IDR_HTML_MIDPACKETINFO          104
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOGIN                129
#define IDD_DIALOG_CONFIG               130
#define IDD_DIALOG_MODIFY_PASS          131
#define IDD_DIALOG_TASK_HISTORY         132
#define IDD_DIALOG_TASK_AND_DEVICE_SETUP 133
#define IDB_BITMAP_LOGIN                134
#define IDB_BITMAP_MAIN                 135
#define IDR_MENU_TASK                   136
#define IDR_MENU_DEVICE                 137
#define IDD_DIALOG_MODIFY_PLACE_SIMPLE  138
#define IDB_BITMAP_LG_LOGIN             139
#define IDB_BITMAP_LG_QUIT              140
#define IDB_BITMAP_XG_PASS              141
#define IDB_BITMAP_CX_HISTORY           142
#define IDB_BITMAP_TASK                 143
#define IDB_BITMAP_MAIN_QUIT            144
#define IDB_BITMAP_DEVICE               145
#define IDB_BITMAP_MAIN_SMALL           146
#define IDB_BITMAP_DEVICE_YINCANG       147
#define IDB_BITMAP_BJ_HIS               149
#define IDB_BITMAP_LAST_PAGE            150
#define IDB_BITMAP_BTN_MOD_COMFIRM      151
#define IDB_BITMAP_FIRST_PAGE           152
#define IDB_BITMAP_PREV_PAGE            153
#define IDB_BITMAP_BJ_PASS              155
#define IDB_BITMAP_NEXT_PAGE            156
#define IDB_BITMAP_BJ_SIMPLE_PLACE      157
#define IDB_BITMAP_MOD_PASS_TC          158
#define IDB_BITMAP2                     159
#define IDB_BITMAP_MOD_PASS_QD          159
#define IDB_BITMAP_FP_OK                160
#define IDB_BITMAP_PZ_OK                162
#define IDB_BITMAP_PZ_BJ                163
#define IDB_BITMAP_FP_BJ                165
#define IDD_DIALOG1                     166
#define IDB_BITMAP1                     167
#define IDB_BITMAP_1CODE_BJ             167
#define IDB_BITMAP_1CODE_OK             168
#define IDB_BITMAP_M_QUEDING            169
#define IDB_BITMAP4                     170
#define IDB_BITMAP_M_QUEXIAO            170
#define IDD_DIALOG_FEI_SUYUAN           171
#define IDB_BITMAP_FSY_BJ               174
#define IDB_BITMAP_FSY_TIANJIA          175
#define IDB_BITMAP_FSY_CANCEL           176
#define IDB_BITMAP_ADD_PT_TASK          179
#define IDD_DIALOG_MID_PACKET           180
#define IDB_BITMAP_ZB_INFO              182
#define IDB_BITMAP_ZB_PRINT             183
#define IDR_TUOPAN_MENU                 184
#define IDC_BUTTON_PRINT                1003
#define IDC_BUTTON_CANCEL               1004
#define IDC_BUTTON_CONFIG               1005
#define IDC_EDIT_PACKET_TOTAL           1006
#define IDC_EDIT_PACKET_PRINTED         1007
#define IDC_LIST_DEVICE                 1008
#define IDC_BUTTON_MIN                  1009
#define IDC_LIST_TASK                   1010
#define IDC_EDIT_TASK                   1011
#define IDC_EDIT_DEVICE                 1012
#define IDC_EDIT_STATUS                 1013
#define IDC_BUTTON_CHANGE_PASS          1013
#define IDC_LIST_PRINT_INFO             1014
#define IDC_EDIT_LOGIN_NAME             1015
#define IDC_EDIT_LOGIN_PASS             1016
#define ID_LOGIN                        1017
#define IDC_CHECK_NAME                  1018
#define IDC_CHECK_WEIGHT                1019
#define IDC_CHECK_SPEC                  1020
#define IDC_CHECK_PLACE                 1021
#define IDC_CHECK_BATCH                 1022
#define IDC_CHECK_DATE                  1023
#define IDC_CHECK_QR_CODE               1024
#define IDC_BUTTON_UPDATE               1026
#define IDC_BUTTON_UPDATE_DEVICE        1026
#define IDC_STATIC_CUR_TASK             1027
#define IDC_STATIC_CUR_DEVICE           1028
#define IDC_STATIC_TOTAL_PAKETS         1029
#define IDC_STATIC_PRINTED_PACKETS      1030
#define IDC_BUTTON_MODIFY               1031
#define IDC_EDIT_OLD_PASS               1032
#define IDC_EDIT_NEW_PASS               1033
#define IDC_EDIT_NEW_PASS_AGAIN         1034
#define ID_BUTTON_MODIFY_OK             1035
#define IDC_BUTTON_UPDATE_TASK          1045
#define IDC_BUTTON_ADD_COMM_TASK        1046
#define IDC_BUTTON_TASK_HISTORY         1047
#define IDC_LIST_TASK_HISTORY           1048
#define IDC_COMBO_SETUP_DEVICE          1055
#define IDC_BUTTON_MATCH                1057
#define IDC_EDIT_2D_CODE                1068
#define IDC_EDIT_SIMPLE_PLACE           1069
#define IDC_EDIT_SY_CODE1               1070
#define IDC_EDIT_CODE2                  1071
#define IDC_EDIT_SY_DATE_TO             1071
#define IDC_STATIC_CODE_2D              1072
#define IDC_EDIT_SY_PIWEN_NUM           1072
#define IDC_BUTTON_SHOUYE               1073
#define IDC_EDIT_SY_STANDARD            1073
#define IDC_BUTTON2                     1074
#define IDC_BUTTON_MOYE                 1074
#define IDC_EDIT_SY_DEF1                1074
#define IDC_BUTTON_SHANGYE              1075
#define IDC_EDIT_SY_DEF2                1075
#define IDC_BUTTON_XIAYE                1076
#define IDC_EDIT_SY_DEF3                1076
#define IDC_EDIT_SIMPLE_PLACE2          1077
#define IDC_EDIT_SPEC                   1077
#define IDC_COMBO_CUR_PER_TOTAL         1080
#define IDC_BUTTON_HISTORY_QUIT         1081
#define IDC_BUTTON_SP_QUIT              1081
#define IDC_BUTTON_MODPASS_QUIT         1082
#define IDC_BUTTON_FEIPEI_QUIT          1083
#define IDC_BUTTON_PZ_QUIT              1084
#define IDC_CHECK_1_CODE                1085
#define IDC_EDIT_F_NAME                 1089
#define IDC_EDIT_F_WEIGHT               1090
#define IDC_EDIT_F_SPEC                 1091
#define IDC_EDIT_F_PLACE                1092
#define IDC_EDIT_F_BATCH                1093
#define IDC_EDIT_F_DATE                 1094
#define IDC_EDIT_F_1CODE                1095
#define IDC_EDIT_F_DEFINE1_VALUE        1099
#define IDC_EDIT_F_DEFINE2_VALUE        1100
#define IDC_EDIT_F_DEFINE3_VALUE        1101
#define IDC_EDIT_F_NUM                  1102
#define IDC_EDIT_F_DATE_TO              1103
#define IDC_CHECK_DEFINE1               1104
#define IDC_EDIT_F_OFFDOC               1104
#define IDC_CHECK_DEFINE2               1105
#define IDC_EDIT_F_STANDARD             1105
#define IDC_CHECK_DEFINE3               1106
#define IDC_DATETIMEPICKER_FSY          1107
#define IDC_DATETIMEPICKER_FSY_TIME     1108
#define IDC_DATETIMEPICKER_FSY_DATE_TO  1109
#define IDC_CHECK_DATE_TO               1110
#define IDC_EDIT_MID_CODE               1111
#define IDC_CHECK_OFFDOC                1111
#define IDC_CHECK_STANDARD              1112
#define IDC_STATIC_STATUS               1113
#define IDC_DATETIMEPICKER_SY_DATE      1114
#define IDC_BUTTON_MID_CANCEL           1118
#define IDC_CHECK_CMY_SIM_NAME          1119
#define IDC_RADIO_TIME1                 1120
#define IDC_RADIO_TIME2                 1121
#define IDC_RADIO_FSY_TIME2             1122
#define IDC_RADIO_WEIGHT_G              1122
#define IDC_RADIO_FSY_TIME1             1123
#define IDC_RADIO_WEIGHT_KG             1123
#define IDC_STATIC1                     1124
#define IDC_RADIO_FSY_TIME3             1124
#define IDC_STATIC2                     1125
#define IDC_RADIO_WEIGHT_NO             1126
#define IDC_RADIO_TIME3                 1127
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32771_TASK_FENPEI            32773
#define ID_32772_TASK_GUANBI            32774
#define ID_TASK_FENPEI                  32775
#define ID_TASK_GUANBI                  32776
#define ID_TASK_FEN_PEI                 32777
#define ID_TASK_GUAN_BI                 32778
#define ID_32779                        32779
#define ID_TASK_QU_XIAO                 32780
#define ID_32781                        32781
#define ID_TASK_DOWNLOAD                32782
#define ID_32783                        32783
#define ID_32784                        32784
#define ID_DEVICE_PRINT_START           32785
#define ID_DEVICE_PRINT_STOP            32786
#define ID_Menu                         32787
#define ID_SIMPLE_PLACE                 32788
#define ID_32789                        32789
#define ID_MODEL_SET                    32790
#define ID_32791                        32791
#define ID_TASK_DOWNLOAD_               32792
#define ID_32793                        32793
#define ID_1CODE                        32794
#define ID_32795                        32795
#define ID_QUXIAO_TASK                  32796
#define ID_32797                        32797
#define ID_FEI_SUYUAN                   32798
#define ID_32800                        32800
#define ID_EDIT_FSY_TASK                32801
#define ID_32802                        32802
#define ID_ADD_FSY_TASK                 32803
#define ID_ADD1_FSY_TASK                32804
#define ID_EDIT_SY_TASK                 32807
#define ID_32808                        32808
#define ID_32809                        32809
#define ID_EDIT_TASK                    32810
#define ID_32811                        32811
#define ID_MID_PACK                     32812
#define ID_32813                        32813
#define ID_32814                        32814
#define ID_OUT_SYSTEM                   32815
#define ID_BACK_SYSTEM                  32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
